### ISSUE TITLE
Doesn't Work on Flatpak Firefox

### ISSUE THREAD

**Issue by elsiehupp** [johvik/CloseLastTab#1]
It was working on regular Firefox for Linux (the Snap, I think), but it's not working on the Flatpak version. I can take a look through the code to see if there are any obvious conflicts.

**Comment by johvik** [comment]
I tried it with org.mozilla.firefox from flathub and org.mozilla.Firefox on Fedora and I'm not able to reproduce it here :confused:
Could you provide more information on what you are running and what behavior you are seeing?

**Comment by johvik** [comment]
Please provide more information and reopen the issue, if its still reproducible :+1:

**Comment by elsiehupp** [comment]
It took me a second to get around to looking up the additional information. I’m running Mozilla Firefox Flatpak 1.0, AKA 88.0 (64-bit) on Debian Bullseye with GNOME 3.38.5 and X11.

Somewhat strangely, Firefox says “your browser is being managed by your organization”, and there are a number of enterprise settings in place. My computer is not part of an enterprise domain, so I assume that this has something to do with Flatpak.

Anyway, [here’s a link to the “Troubleshooting Information” output](https://gist.github.com/elsiehupp/dc3e93b91f37f80d2e30e84e0bcdf1a2#file-firefox-troubleshooting-informaton-2021-05-02-txt), which should hopefully be sufficiently exhaustive.

**Comment by johvik** [comment]
Thank you for the information, it appears like `browser.tabs.closeWindowWithLastTab` is not set to false in about:config. It is required for the addon to work. Please try that and let me know if it helps.

**Comment by elsiehupp** [comment]
Thanks, that seems to have fixed it! Is that option something that I overlooked in the documentation, or should it potentially be added to a troubleshooting guide somewhere? I mean, the plugin works perfectly fine on every other computer of mine, and I don’t remember changing that setting…

**Comment by johvik** [comment]
Glad to hear that it works! The option requirement is in the addons description :blush:
